### ISSUE TITLE
Can't install tool

### ISSUE THREAD

**Issue by damilare** [rephus/Github-PR-tracker#1]
On a fresh clone, I get the following errors

$ npm install 

```
npm WARN Invalid name: “Github PR tracker”
npm WARN Github-PR-tracker No description
npm WARN Github-PR-tracker No repository field.
npm WARN Github-PR-tracker No README data
npm WARN Github-PR-tracker No license field.
```
node app.js

```
$ node app.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/dami/Projects/Tools/Github-PR-tracker/app.js:2:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by rephus** [comment]
Thanks for noticing, it was an issue on the name field in the package.json. Fixed in he last commit on master.
